### ISSUE TITLE
Tools fail to download

### ISSUE THREAD

**Issue by marinorasin** [blake502/balatro-apk-maker#13]
I watched a video going step by step on how to create the apk but when I got to the part where you use the apk maker, it does the script and when it finishes, the apk zip file disappears
Is there a problem with my pc or is the build a little buggy rn?

https://github.com/blake502/balatro-apk-maker/assets/53486816/ec6c5db1-3136-47fe-8d95-d0f433b8c6a8

Here's a video so you can see whats wrong, hope it helps

**Comment by ZahRizi** [comment]
Thats whats supposed to happen when you select clean up temp. files

**Comment by marinorasin** [comment]
> Thats whats supposed to happen when you select clean up temp. files

How do I get the Balatro apk then? Do I just set it to keep temp files?

**Comment by blake502** [comment]
I can't see the entire error from your video. Can you copy and paste the entire output from the program? Or make the console taller to capture more of the error?

Thanks!

**Comment by blake502** [comment]
My initial suspicion is that your internet connection is blocking you from downloading Balatro-APK-Patch.zip ...
Can you try to download it directly here: https://smudge.codes/files/Balatro-APK-Patch.zip

**Comment by marinorasin** [comment]
> My initial suspicion is that your internet connection is blocking you from downloading Balatro-APK-Patch.zip ... Can you try to download it directly here: https://smudge.codes/files/Balatro-APK-Patch.zip

I think it worked finally (idk why it didnt before) but now idk what to do next

https://github.com/blake502/balatro-apk-maker/assets/53486816/a65d802d-eca7-4392-80a4-6797c2e309eb

**Comment by marinorasin** [comment]
> Yeah that's not working right. It's spitting out all kinds of errors. It looks like a connection issue. Is your internet stable?
> 
> Can you try beta-0.3 from the releases section?

Well, Im living in a dorm so this is as good as it gets but I can play games with it without many problems
Ill try the beta-0.3 version and record the screen again

**Comment by blake502** [comment]
Your dorm connection is blocking access to my website, where some of the tools are downloaded. It's pretty typical for connections like that to block new/unknown domains.

I'll rework it to download those tools from GitHub instead. I'll plan on getting a new version working tomorrow.

**Comment by blake502** [comment]
Please try again using the latest release (beta-0.4.2 at the time of writing this)

**Comment by marinorasin** [comment]
> Please try again using the latest release (beta-0.4.2 at the time of writing this) Edit: Be sure to delete everything in the folder before you try again, in case any of those other tools are corrupted.

It worked and Balatro is on my phone now but it didnt let me transfer my save file and there is some lag (but that is because my phone is a bit shit)

**Comment by blake502** [comment]
I just released a new revision that should make save transferring more stable. I'll go ahead and close this issue, but feel free to open a new one if you encounter issues with save transferring on beta-0.5.1.
