### ISSUE TITLE
Failed to unpack Love2D APK with APK Tool!

### ISSUE THREAD

**Issue by water221c** [blake502/balatro-apk-maker#16]
![image_2024-04-12_184750137](https://github.com/blake502/balatro-apk-maker/assets/71347711/f47d3eca-e3a1-460d-a8cc-c76f67074bbf)
this is what happens when I start the balatro-apk-maker-beta-0.5.exe to make the apk
do you know why this happens or how to fix it?

**Comment by blake502** [comment]
I see: `apktool.jar already exists`

Try to delete everything in the folder, then try again. It seems like `apktool.jar` may be corrupted.

**Comment by water221c** [comment]
it worked thanks!

**Comment by blake502** [comment]
Perfect, have a great day!
