### ISSUE TITLE
Stuck when transferring save data

### ISSUE THREAD

**Issue by cfern11** [blake502/balatro-apk-maker#18]
Whenever I try to transfer my save from steam it gets stuck here:

Would you like to replace the existing file:
  Path:     platform-tools\platform-tools\adb.exe
  Size:     5857056 bytes (5720 KiB)
  Modified: 2024-03-20 16:42:38
with the file from archive:
  Path:     platform-tools\adb.exe
  Size:     5857056 bytes (5720 KiB)
  Modified: 2024-03-20 16:42:38

**Comment by blake502** [comment]
Are you using beta-0.5.1? This was an issue in beta-0.5, but should be solved in the latest version.

**Comment by cfern11** [comment]
Wow you're fast I just downloaded beta-0.5. Everything's working now thanks for all the hard work!

**Comment by blake502** [comment]
Happy to help!
