### ISSUE TITLE
[Error] Save Transfer via ADB

### ISSUE THREAD

**Issue by tsngsn** [blake502/balatro-apk-maker#19]
[beta-0.5.2] Balatro APK install via ADB was successful, yet the save transfer was not. I was able to replicate this error by running the APK maker again.

```
Attempting to transfer saves. If prompted, please allow the USB Debugging connection on your Android device.
adb: error: target '/data/local/tmp/balatro/files/save/game' is not a directory
Deleting tools...
Deleting temporary files...
Press any key to exit...
```

Moreover, I cannot find the save folder directory on my Android phone to manually transfer my data.

**Comment by blake502** [comment]
Thanks for reporting this! Give it a shot now on beta-0.5.3

**Comment by tsngsn** [comment]
```
Attempting` to transfer saves. If prompted, please allow the USB Debugging connection on your Android device.
    adb: error: cannot stat 'C:\Users\John': No such file or directory
    adb: error: cannot stat 'Doe\AppData\Roaming/Balatro/.': No such file or directory
```
Thanks for being so active in updating this! I tried it again with beta-0.6, but the ADB save transfer failed to locate the Steam saves on my PC. This is likely due to my PC username having a space (i.e. John Doe). Not sure what exact directory it's coded to look in, but pulling saves from %APPDATA%\Balatro\ should work every time regardless of the username right?

**Comment by blake502** [comment]
Ah I had not considered somebody having a space in their username haha.
The directory needs to be placed in quotes. I'll get that taken care of soon!

**Comment by blake502** [comment]
Give it a shot on beta-0.6.1

**Comment by tsngsn** [comment]
On beta-0.6.1, it works perfectly now. Thanks!
