### ISSUE TITLE
Python  fork

### ISSUE THREAD

**Issue by antipatico** [blake502/balatro-apk-maker#21]
Hi @blake502 ,

I created a python fork of this project, that allows users to create APKs on linux too. I assume it should work cross platform (Mac and Windows too). Are you okay if I publish it?

EDIT: obviously, I would clearly state that and also link to your original project.

Best,
antipatico

**Comment by blake502** [comment]
I have no problem with this, go for it.

**Comment by antipatico** [comment]
Published here: https://github.com/antipatico/balatromobile

Thanks
