### ISSUE TITLE
[beta-0.6.1, Android 14] Save inacessible

### ISSUE THREAD

**Issue by qouesm** [blake502/balatro-apk-maker#29]
This has been working wonderfully on my Android 13 phone (Oneplus 7 Pro; DivestOS) and I applaud the work that's been done here. I've been transferring my save to and from my phone just fine. Through a number of releases, I have not been able to access my save location on my Android 14 tablet (Pixel Tablet; CalyxOS) and I have not been able to nail down a reason unfortunately.

As best as I can tell, the files at `Android/data/com.unofficial.balatro/files/save/` are inaccessible. If I navigate to this directory via system file manager, it is empty. It _is_ keeping a saved run between system reboot so I know it's there. Other apps in that `Android/data` directory appear to work fine, like how I can view images in from cache my music app generates.

I have tried: 
- the system file manager app (AOSP)
- [Fossify File Manager](https://f-droid.org/packages/org.fossify.filemanager/) (A 3rd party one)
- [FV File Manager](https://play.google.com/store/apps/details?id=com.folderv.file) which purports to allow access to `Android/[data,obb]` with Shizuku
- `android-file-transfer` (which I've been using to move my save with my phone)
```sh
# downloading aforementioned cached image from another app in `Android/data`
downloading to  "/tmp"
downloading  1  file(s),  414162  bytes
downloading  258 to "/tmp/0009CD2AD51EF6BAA99A2256C1CBAD92.jpg"
finishing queue
finished
# opening Android/data/com.unofficial.balatro/files/save/
setParent failed: "Get: invalid response code InvalidObjectHandle (0x2009)"
```
- `adb push`:
```sh
# doing a working push
% adb push tom.png sdcard/Download/
tom.png: 1 file pushed, 0 skipped. 139.3 MB/s (255257 bytes in 0.002s)
# pushing my save folder
% pwd
/home/qouesm/.local/share/Steam/steamapps/compatdata/2379780/pfx/drive_c/users/steamuser/AppData/Roaming/Balatro
% ls
1  settings.jkr  steam_autocloud.vdf
% adb push 1 sdcard/Android/data/com.unofficial.balatro/files/save/
zsh: killed     adb push 1 sdcard/Android/data/com.unofficial.balatro/files/save/
```

Release: beta-0.6.1
Host: Windows 11 under VirtualBox
Device: Google Pixel Tablet
Android Version: 14
CalyxOS version: 5.6.0

**Comment by blake502** [comment]
[You're looking in the wrong spot](https://love2d.org/wiki/love.filesystem).

You should be looking at `/data/data/com.unofficial.balatro/files/save/`

As far as I know, it's only accessible through ADB. Check out the source... Since it's a little convoluted in the source, I'll put it this way-- We do something like this:

```
(Push everything from the "...\AppData\Balatro\" directory into a tmp location)
adb push "%AppData%/Balatro/." /data/local/tmp/balatro/files/save/game

("Run-as" the app, then copy everything from the tmp location to the current directory...
... "Run-as" automatically sets the working directory to the right directory)
adb shell run-as com.unofficial.balatro cp -r /data/local/tmp/balatro/files .
```

**Comment by qouesm** [comment]
OK that worked, thank you! I remember in previous updates there was an "accessible saves" patch that I recall not seeing with the newest release. Does it default to "inaccessible" saves for lack of a better term now? Because I'm just now noticing that my save didn't carry over when updating on my phone now. The same steps worked to move my save to my phone.
