### ISSUE TITLE
How to make different version ipa

### ISSUE THREAD

**Issue by garyhe231** [blake502/balatro-apk-maker#30]
Just a question, is there a way that I can make different ipa for the different versions? Now no matter what is the ipa name I renamed, it only overrides the existing one app on iOS. How can I make a different ipa for different game version? For example, can I have two apps on iOS, one for the 1.0.0 version and one for the 1.0.1 version? I have both Balatro.exe backed up.

**Comment by blake502** [comment]
Just to be clear, you're talking about having two separate Balatro apps installed on your iOS device?

That would be a question for [Sheep975](https://github.com/Sheep975). I imagine a separate IPA base would need to be made with a unique identifier.

That's a bit out-of-scope for this project, sorry.
