### ISSUE TITLE
change game files

### ISSUE THREAD

**Issue by Victor3050** [blake502/balatro-apk-maker#4]
How can I change the game files to change and make the language button appear on my Balatro mobile?

**Comment by blake502** [comment]
Try the latest release. That should enable language switching.

If you'd like to modify the code, you can run the balatro-apk-maker until it asks you to select your patches.. At that point, the Balatro folder will be available for you to modify. Once you make your changes, you can return to the balatro-apk-maker to select patches and finish building the APK.
