### ISSUE TITLE
Black screen on Pixel devices

### ISSUE THREAD

**Issue by RiceManDan** [blake502/balatro-apk-maker#5]
![Screenshot-20240317-173040](https://github.com/blake502/balatro-apk-maker/assets/10265782/46bab322-370e-456e-b0f9-10d6b09c3e33)

Issue happens on Pixel 6 pro, Pixel 6, and Pixel 8 pro.

**Comment by OatmealParmesan** [comment]
I had this issue on my Pixel 7 w/ a capped framerate. Went fine with uncapped.

**Comment by scummboy** [comment]
I am getting this exact problem with Beta 3 regardless of capping or not capping framerate. My phone is a Pixel 8 Pro.

**Comment by RiceManDan** [comment]
This issue is solved by applying the CRT filter disable patch.

**Comment by scummboy** [comment]
that has fixed it, thank you very much!
