### ISSUE TITLE
Unable to download required dependencies

### ISSUE THREAD

**Issue by VBPXKSMI** [blake502/balatro-apk-maker#8]
Hello, 
As the title says, I am unable to progress past the first step upon executing balatro-apk-maker.exe.
That is, it checks that I already have Java installed, tries to download the rest of the dependencies, but not long after that it fails as for some reason it is unable to download them and then I am forced to close the prompt window.

I don't know what could be the issue really, only guess I have is that it may possibly be related to a Windows feature that I am lacking as I use Windows 8.1 and maybe either balatro-apk-maker.exe was made/compiled using a function only available for higher Windows versions, or one or more of the dependecies requires a higher Windows version to work. Other than this guess I have no clue.
If the problem is related to that I would kindly ask if there is no workaround available, to compile the .exe so that it is possible to use it on previous Windows versions, or to at least point out user requirements in the Github readme page to warm future users.

I can guarantee that at least I have 7-Zip and Java 8 already installed and both work with no problems, and that I have more than enough disk space to download the dependencies.

I have provided an screenshot of the command prompt window and where the process fails, hope it helps.
Thank you and cheers.
![Screenshot](https://github.com/blake502/balatro-apk-maker/assets/58800629/0231ad4b-dfbb-444f-9fbe-b596f6c677e8)

**Comment by spydersoda** [comment]
is the apk maker in the Balatro steam folder?

**Comment by blake502** [comment]
Hmm, Windows 8.1 should be supported although I haven't tested it. Downloading files relies on PowerShell's [Invoke-WebRequest](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.4), which was introduced in PowerShell 3.0 (Windows 8.1 should come with PowerShell 4.0)

If running as administrator does not work, can you try opening Command Prompt and running this command:
```
powershell -Command Invoke-WebRequest https://google.com/ -OutFile google.html
```
Let me know if the command generates any errors. In the mean time, I may work on re-writing the download function to use a native C# library to download files instead... The PowerShell command is leftover from when balatro-apk-maker was a batch file.

**Comment by blake502** [comment]
I've updated balatro-apk-maker to use WebClient for downloads instead of `powershell Invoke-WebRequest`.
Please try again using [the latest version](https://github.com/blake502/balatro-apk-maker/releases/download/beta-0.4/balatro-apk-maker-beta-0.4.exe).

**Comment by VBPXKSMI** [comment]
I just tested the latest version and it worked like a charm! Thanks.
Tested by running as administrator inside the steam folder.

Dunno what the problem was with the previous version, as I ran it both as administrator and inside the steam folder too, but ran into the issue I commented at the beggining. 
Perhaps it really was due to how the apk maker fetched the downloads before.

Also I tested the 

`powershell -Command Invoke-WebRequest https://google.com/ -OutFile google.html`

prompt and it showed no errors, just to let you know.

Anyway, issue solved, you can close it now. Thanks again.

**Comment by blake502** [comment]
Great, I'm glad it's working now! The change should make files download faster for everybody anyway.
